classProfiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'classProfiles'
urlpatterns = [
    url(r'^$', views.profiles, name='list'),
    url(r'^(?P<profile_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^delete/$', views.delete_profile, name='delete'),
    url(r'^add/$', views.add_profile, name='add'),
    url(r'^edit/$', views.edit_profile, name='edit'),
    url(r'^profile-edit-subjects-hours/$', views.save_new_hoursno_on_profile, name='profile-edit-subjects-hours'),
    url(r'^profile-add-subjects/$', views.add_subject_to_profile, name='profile-add-subjects'),
    url(r'^profile-delete-subject/$', views.delete_subject_from_profile, name='profile-delete-subject')
]

groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'
urlpatterns = [
    url(r'^$', views.group_list, name='group_list'),
    url(r'^delete/$', views.delete_group, name='delete'),
    url(r'^add/$', views.add_group, name='add'),
    url(r'^edit/$', views.edit_group, name='edit'),
]

smok/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from users.views import login
from commons.views import common
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^login', login),
    url(r'^login', auth_views.login, name='login'),
    url(r'^logout', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^subjects/', include('subjects.urls')),
    url(r'^schools/', include('school.urls')),
    url(r'^index', common, name='index'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='root'),
    url(r'^teachers/', include('teachers.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^classrooms/', include('classrooms.urls')),
    url(r'^availability/', include('availability.urls')),
    url(r'^profiles/', include('classProfiles.urls')),
    url(r'^timetables/', include('timetables.urls')),
]

groups/models.py
# -*- coding: utf-8 -*-
from django.db import models
from school.models import  School
from classProfiles.models import Class_profile


class Group(models.Model):
    class Meta:
        unique_together = ('name',)

    name = models.CharField(max_length=200, verbose_name="Klasa")
    #group_profile = models.CharField(max_length=200, blank=True, default='')
    group_profile = models.ForeignKey(Class_profile, verbose_name="Profil", on_delete=models.SET_NULL, blank=True, null=True)
    number_of_students = models.PositiveIntegerField(blank=True, null=True, default=0)
    school = models.ForeignKey(School, on_delete=models.CASCADE, verbose_name="Szkoła", blank=True, null=True, default=None)
    
    def __str__(self):
        return self.name

groups/forms.py
from django import forms
from .models import Group

class GroupForm(forms.ModelForm):

    
    class Meta:
        model = Group
        fields = ('name', 'group_profile', 'number_of_students',)

groups/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, Http404
from .models import Group
from school.models import School
from .forms import GroupForm
from django.core import serializers
from django.db import IntegrityError
import json
from django.contrib.auth.decorators import login_required

@login_required
def group_list(request):
    username = request.user.username if request.user.is_authenticated else 'niezalogowano'
    all_groups_list = Group.objects.order_by('name')
    context = {'models': all_groups_list, 'username': username}
    return render(request, 'groups/groups.html', context)

def add_group(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            form = GroupForm(request.POST)
            if form.is_valid():
                try:
                    new_group = form.save(commit=False)
                    new_group.school = request.user.school_id
                    new_group.save()
                    data = serializers.serialize('json', [new_group])
                    data = json.loads(data)
                    data[0]['group_profile_name'] = str(new_group.group_profile)
                    return HttpResponse(json.dumps(data))
                except IntegrityError:
                    pass
            else:
                return HttpResponse(json.dumps([{'error': 'UNIQUE_NAME_VIOLATED'}]))
        else:
            return HttpResponse(json.dumps(['foo', {'bar': ('baz', None, 1.0, 2)}]))
    else:
        form = GroupForm()
    return HttpResponse(form) 

def edit_group(request):
    if request.method == "POST":
        try:
            record_id = request.POST['id']
            group = Group.objects.get(pk=record_id)
            form = GroupForm(request.POST, instance=group)
            if form.is_valid():
                new_group = form.save()
                data = serializers.serialize('json', [new_group])
                data = json.loads(data)
                data[0]['group_profile_name'] = str(new_group.group_profile)
                return HttpResponse(json.dumps(data))
            else:
                return HttpResponse("FAILED")
        except ObjectDoesNotExist:
            raise Http404("Brak klasy o id %s w bazie." % record_id)
    elif request.method == "GET":
        try:
            record_id = request.GET['id']
            group = Group.objects.get(pk=record_id)
            form = GroupForm(instance=group)
        except ObjectDoesNotExist:
            raise Http404("Brak klasy o id %s w bazie." % record_id)
        return HttpResponse(form)

def delete_group(request):
    if request.method == "POST":
        record_id = request.POST.get("id")
        try:
            group = Group.objects.get(pk=record_id)
        except ObjectDoesNotExist:
            raise Http404("Brak klasy o id %s w bazie." % record_id)
        group.delete()
        return HttpResponse()

groups/templates/groups/groups.html
<!DOCTYPE html>
{% extends "base_resources_list.html" %}
{% load static %}

{% block css %}
{{block.super}}
{% endblock %}

{% block js %}
{{block.super}}
<script>
    var addURL = "{% url 'groups:add' %}";
    var editURL = "{% url 'groups:edit' %}";
    var deleteURL = "{% url 'groups:delete' %}";
</script>
<script src="{% static "/js/groups.js" %}"></script>
{% endblock %}

{% block resource-name-header%}Klasy{% endblock %}

{% block add-resource %}<span id="newItem" class="button">&#43; nowa klasa</span>{% endblock %}

{% block list-header-definition %}
<span class="row-content">Klasa</span>
<span class="row-content">Liczba uczniów</span>
<span class="row-content">Profil</span>
{% endblock %}

{% block model-definition %}
<li id="{{ model.id }}">
    <span class="row-content"> <span id="resource-name-{{ model.id }}" class="list-element">{{ model.name }}</span> </span>
    <span class="row-content"> <span id="resource-studentsnumber-{{ model.id }}" class="list-element">{{ model.number_of_students }}</span> </span>
    <span class="row-content"> <span id="profile-container-{{ model.id }}" class="list-element">
        {% if model.group_profile %}
            <a class="no-format" id="a-resource-profile-{{ model.id }}" href="{% url 'classProfiles:profile' model.group_profile.id %}">
                <span id="resource-profile-{{ model.id }}">{{ model.group_profile }}</span>
            </a>
        {% else %}
            <span class="row-content"><p>brak</p></span>
        {% endif %}
    </span></span>
    <span class="edit" onClick="edit_item({{ model.id }});">&#x1f589;</span>
    <span id="resource-delete-{{ model.id }}" class="close" onClick="delete_item({{ model.id }}, '{{ model.name }}');">&#x232b;</span>
</li>
{% endblock %}

{% block empty-models-comment %}Brak zapisanych klas.{% endblock %}

{% block success-modal-header%}Informacja{% endblock %}
{% block success-modal-body%}
Klasa o podanej nazwie już istnieje.
{% endblock %}

{% block add-modal-header%}Dodaj nową klasę{% endblock %}
{% block add-modal-body%}
<form action='' method="POST" class="add_group" autocomplete="off">{% csrf_token %}
    <div id="addForm" class="form"></div>
    <input class="send button" type="submit" value="Dodaj" />
</form>
{% endblock %}

{% block edit-modal-header%}Edytuj klasę <span class="groupName"></span>{% endblock %}
{% block edit-modal-body%}
<form action='' method="POST" class="edit_group" autocomplete="off">{% csrf_token %}
    <div id="editForm" class="form"></div>
    <input class="send button" type="submit" value="Zapisz" />
</form>
{% endblock %}

{% block delete-modal-header%}Czy na pewno chcesz usunąć klasę <span class="groupName"></span>?{% endblock %}
{% block delete-modal-body%}
<button class="cancel send" onClick="closeDeleteModal();">Anuluj</button>
{% endblock %}