smok/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from users.views import login
from commons.views import common
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^login', login),
    url(r'^login', auth_views.login, name='login'),
    url(r'^logout', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^subjects/', include('subjects.urls')),
    url(r'^schools/', include('school.urls')),
    url(r'^index', common, name='index'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='root'),
    url(r'^teachers/', include('teachers.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^classrooms/', include('classrooms.urls')),
    url(r'^availability/', include('availability.urls')),
    url(r'^profiles/', include('classProfiles.urls')),
    url(r'^timetables/', include('timetables.urls')),
]

timetables/urls.py
from django.conf.urls import url

from . import views

app_name = 'timetables'
urlpatterns = [
    url(r'^$', views.timetables, name='list'),
    #url(r'^export/$', views.export_timetable, name='export-timetable'),
    url(r'^(?P<timetable_id>[0-9]+)/$', views.timetable, name='timetable'),
    url(r'^delete/$', views.delete_timetable, name='delete'),
    url(r'^add/$', views.add_timetable, name='add'),
    url(r'^edit/$', views.edit_timetable, name='edit'),
    url(r'^addPosition/$', views.add_timetable_position, name='addPosition'),
    url(r'^getPosition/$', views.get_timetable_position, name='getPosition'),
]

timetables/models.py
# -*- coding=utf-8 -*-

from django.db import models

from groups.models import Group
from commons.models import Hours, Days
from teachers.models import Teacher
from subjects.models import Subject
from classrooms.models import Classroom
from school.models import School
from django.utils.timezone import now

class Timetable(models.Model):
	school = models.ForeignKey(School, on_delete=models.CASCADE, verbose_name="Szkoła", default='-1')
	name = models.CharField(unique=True, max_length=150)
	last_updated_timestamp = models.DateTimeField(default=now)
	is_processed = models.BooleanField(default=False)
	is_marked_to_process = models.BooleanField(default=True)

	def __str__(self):
		return '%s' % (self.name)
	
class TimetablePosition(models.Model):
	timetable = models.ForeignKey(Timetable)
	group = models.ForeignKey(Group)
	hour = models.ForeignKey(Hours)
	day = models.ForeignKey(Days)
	teacher = models.ForeignKey(Teacher)
	subject = models.ForeignKey(Subject)
	classroom = models.ForeignKey(Classroom)
	
	class Meta:
		unique_together = (
			('timetable','hour','day','group'),
			('timetable','hour','day','teacher'),
			('timetable','hour','day','classroom'),
		)

class TimetableLog(models.Model):
	timetable = models.ForeignKey(Timetable);
	text = models.CharField(max_length=1000);

timetables/forms.py
from django import forms
from .models import Timetable


class TimetableForm(forms.ModelForm):
    
    class Meta:
        model = Timetable
        fields = ('name',)

timetables/views.py
from django.shortcuts import render
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required
from .models import Timetable, TimetablePosition
from django.http import HttpResponse, Http404, JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from .forms import TimetableForm
from django.core import serializers
from groups.models import Group
from commons.models import Hours, Days
from school.models import School
from teachers.models import Teacher
from subjects.models import Subject
from classrooms.models import Classroom
import json
#from reportlab.pdfgen import canvas


@login_required
def timetables(request):
    all_timetables_list = Timetable.objects.order_by('name')
    context = {'models': all_timetables_list}
    return render(request, 'timetables.html', context)

@login_required
def timetable(request, timetable_id):
    timetable = Timetable.objects.get(pk=timetable_id)
    context = {'model': timetable}
    return render(request, 'timetable.html', context)

"""
def export_timetable(request):
    print(request)
    # Create the HttpResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment;filename="somefilename.pdf"'

    # Create the PDF object, using the response object as its "file."
    p = canvas.Canvas(response)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 750, "Welcome to Reportlab!")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()
    return response
"""

def add_timetable(request):
    if request.method == "POST":
        form = TimetableForm(request.POST)
        if form.is_valid():
            new_timetable = form.save(commit=False)
            new_timetable.school = request.user.school_id
            new_timetable.save()
            data = serializers.serialize('json', [new_timetable])
            return HttpResponse(data)
        return HttpResponse('FAILED')
    else:
        form = TimetableForm()
    return HttpResponse(form)

def add_timetable_position(request):
    print('add_timetable_position')
    if request.method == "POST" and request.is_ajax():
        #if timetablePosition exist then update
        isUpdate = False
        currentTimetable = Timetable.objects.get(pk=request.POST['timetable'])
        currentGroup = Group.objects.get(name=request.POST['group'])
        timetablePositions = TimetablePosition.objects.all().filter(timetable=currentTimetable)
        currentTimetablePosition = TimetablePosition.objects.none()
        for position in timetablePositions:
            if str(position.hour.order) == str(request.POST['hour']) and str(position.day.order) == str(request.POST['day']) and str(position.group.name) == str(currentGroup.name):
                isUpdate = True
                currentTimetablePosition = position
                break
        
        if isUpdate:
            print('update')
            #update
            currentTimetablePosition.teacher = Teacher.objects.get(first_name=request.POST['teacherFirstName'], last_name=request.POST['teacherLastName'])
            currentTimetablePosition.subject = Subject.objects.filter(name=request.POST['subject'])[0]
            currentTimetablePosition.classroom = Classroom.objects.get(name=request.POST['classroom'])
            currentTimetablePosition.save()            
        else:
            print('add')
            # add new 
            new_timetable_possition = TimetablePosition()
            new_timetable_possition.timetable = Timetable.objects.get(pk=request.POST.get('timetable', False))
            new_timetable_possition.group = Group.objects.get(name=request.POST['group'])
            new_timetable_possition.hour = Hours.objects.get(pk=request.POST['hour'])
            new_timetable_possition.day = Days.objects.get(pk=request.POST['day'])
            new_timetable_possition.teacher = Teacher.objects.get(first_name=request.POST['teacherFirstName'], last_name=request.POST['teacherLastName'])
            new_timetable_possition.subject = Subject.objects.filter(name=request.POST['subject'])[0]
            new_timetable_possition.classroom = Classroom.objects.get(name=request.POST['classroom'])
            new_timetable_possition.save()
    
    return HttpResponse('')

def get_timetable_position(request):
    print('get_timetable_position')
    if  request.method == "GET" and request.is_ajax():
        print(request.GET)
        currentTimetable = Timetable.objects.get(pk=request.GET['timetableId'])
        timetablePositions = TimetablePosition.objects.all().filter(timetable=currentTimetable)
        allHours = Hours.objects.all()
        print(allHours)
        allHoursOrders = []
        allHoursFrom = []
        allHoursTo = []
        for hour in allHours:
            allHoursOrders.append(hour.order)
            allHoursFrom.append(hour.hour_from)
            allHoursTo.append(hour.hour_to)
        allGroups = Group.objects.all()
        print(allGroups)
        allGroupNames = []
        for group in allGroups:
            allGroupNames.append(group.name)
        responseData = []
        if len(timetablePositions) == 0:
            responseData.append(
                {
                    'allGroupNamesArray': allGroupNames,
                    'ordersArray': allHoursOrders,
                    'fromArray': allHoursFrom,
                    'toArray': allHoursTo,
                    'to': '',
                    'from': '',
                    'hour': '',
                    'day': '',
                    'group': '',
                    'teacher': '',
                    'subject': '',
                    'classroom': '',
                }
            )

        else:
            for position in timetablePositions:
                responseData.append(
                    {
                        'allGroupNamesArray': allGroupNames,
                        'ordersArray': allHoursOrders,
                        'fromArray': allHoursFrom,
                        'toArray': allHoursTo,
                        'to': position.hour.hour_to,
                        'from': position.hour.hour_from,
                        'hour': position.hour.order,
                        'day': position.day.order,
                        'group': position.group.name,
                        'teacher': position.teacher.first_name + " " + position.teacher.last_name,
                        'subject': position.subject.name,
                        'classroom': position.classroom.name,
                        'building': position.classroom.building,
                    }
                )


    print(responseData)
    return JsonResponse(responseData, safe=False)

def edit_timetable(request):
    if request.method == "POST":
        try:
            record_id = request.POST['id']
            timetable = Timetable.objects.get(pk=record_id)
            form = TimetableForm(request.POST, instance=timetable)
            if form.is_valid():
                new_timetable = form.save(commit=False)
                new_timetable.last_updated_timestamp = now()
                new_timetable.save()
                data = serializers.serialize('json', [new_timetable])
                return HttpResponse(data)
            else:
                return HttpResponse(json.dumps([{'error': 'UNIQUE_NAME_VIOLATED'}]))
        except ObjectDoesNotExist:
            raise Http404("Brak planu o id %s w bazie." % record_id)
    elif request.method == "GET":
        try:
            record_id = request.GET['id']
            timetable = Timetable.objects.get(pk=record_id)
            form = TimetableForm(instance=timetable)
        except ObjectDoesNotExist:
            raise Http404("Brak planu o id %s w bazie." % record_id)
        return HttpResponse(form)

def delete_timetable(request):
    if request.method == "POST":
        record_id = request.POST.get("id")
        try:
            timetable = Timetable.objects.get(pk=record_id)
            timetable.delete()
        except ObjectDoesNotExist:
            raise Http404("Brak planu o id %s w bazie." % record_id)
        return HttpResponse()

timetables/templates/timetable.html
<!DOCTYPE html>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% extends "base_resource.html" %}
{% load static %}

{% block css %}
{{block.super}}
<link rel="stylesheet" type="text/css" href="{% static '/bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static '/bootstrap/css/style.css' %}" />
{% endblock %}

{% block js %}
{{block.super}}
<script>
    var addTimetablePositionURL = "{% url 'timetables:addPosition' %}";
    var getTimetablePositionURL = "{% url 'timetables:getPosition' %}";
</script>
<script src="{% static "/bootstrap/js/bootstrap.min.js" %}"></script>
<!--script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script-->
<!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script-->
<script src="{% static "/js/timetables.js" %}"></script>
<script src="{% static "/js/scheduler-data.js" %}"></script>
<script src="{% static "/js/calendar.js" %}"></script>
<script src="{% static "/js/jspdf.min.js" %}"></script>
<script src="{% static "/js/html2canvas.js" %}"></script>
<!--script>
    var exportURL = "d{d% url timetables export-timetable d%d}";
</script-->
{% endblock %}

{% block resource-name-header%}Plan zajęć <span id="timetable-title">{{ model.name }}</span>{% endblock %}
  
{% block export-resource %}
<span id="exportTimetable" class="button">Eksport planu do PDF</span>
{% endblock %}

{% block body-content %}
</br>
  <div id="calendar-container">
    <table id="calendar">
    </table>
  </div>
  <div id="edit-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Edytuj wpis</h4>
            </div>
            <div class="modal-body edit-content">
                <span class="label label-default">Przedmiot</span><input id="lessonName" type="text" class="form-control" />
                <span class="label label-default">Nauczyciel</span><input id="teacher" type="text" class="form-control" />
                <span class="label label-default">Sala</span><input id="class" type="text" class="form-control" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Zapisz</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Usuń</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block return-button %}
<select id="groups" class="form-control">
</select>
<a class="no-format" href="{% url 'timetables:list' %}"><span class="button button-right">Powrót do planów</span></a>
{% endblock %}

{% block loading-modal-custom%}<span class="loading-container"><img class="displayed-custom" src="{% static '/img/ajax-loader.gif' %}" alt=""> ładowanie, proszę czekać</span>{% endblock %}

timetables/templates/timetables.html
{% extends "base_resources_list.html" %}
{% load static %}

{% block css %}
{{block.super}}
{% endblock %}

{% block js %}
{{block.super}}
<script>
    var addURL = "{% url 'timetables:add' %}";
    var editURL = "{% url 'timetables:edit' %}";
    var deleteURL = "{% url 'timetables:delete' %}";
</script>
<script src="{% static "/js/timetables.js" %}"></script>
{% endblock %}

{% block resource-name-header%}Plany zajęć{% endblock %}

{% block add-resource %}<span id="newItem" class="button">&#43; wygeneruj plan</span>{% endblock %}

{% block list-header-definition %}
<span class="row-content">Nazwa</span>
<span class="row-content">Ostatnio zmieniono</span>
{% endblock %}

{% block model-definition %}
<li id="{{ model.id }}">
    <a class="no-format" href="{% url 'timetables:timetable' model.id %}">
        <span class="row-content"> <span id="resource-name-{{ model.id }}" class="list-element">{{ model.name }}</span></span>
    </a>
    <span class="row-content"> <span id="resource-lut-{{ model.id }}" class="list-element">{{ model.last_updated_timestamp }}</span> </span>
    <span class="edit" onClick="edit_item({{ model.id }});">&#x1f589;</span>
    <span id="resource-delete-{{ model.id }}" class="close" onClick="delete_item({{ model.id }}, '{{ model.name }}');">&#x232b;</span>
</li>
{% endblock %}

{% block empty-models-comment %}Brak zapisanych planów zajęć.{% endblock %}

{% block success-modal-header%}Informacja{% endblock %}
{% block success-modal-body%}
Plan o podanej nazwie już istnieje.
{% endblock %}

{% block add-modal-header%}Dodaj pusty plan{% endblock %}
{% block add-modal-body%}
<form action='' method="POST" class="add_timetable" autocomplete="off">{% csrf_token %}
    <div id="addForm" class="form"></div>
    <input class="send button" type="submit" value="Dodaj" />
</form>
{% endblock %}

{% block edit-modal-header%}Edytuj plan <span class="timetableName"></span>{% endblock %}
{% block edit-modal-body%}
<form action='' method="POST" class="edit_timetable" autocomplete="off">{% csrf_token %}
    <div id="editForm" class="form"></div>
    <input class="send button" type="submit" value="Zapisz" />
</form>
{% endblock %}

{% block delete-modal-header%}Czy na pewno chcesz usunąć plan <span class="timetableName"></span>?{% endblock %}
{% block delete-modal-body%}
<button class="cancel send" onClick="closeDeleteModal();">Anuluj</button>
{% endblock %}