classProfiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'classProfiles'
urlpatterns = [
    url(r'^$', views.profiles, name='list'),
    url(r'^(?P<profile_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^delete/$', views.delete_profile, name='delete'),
    url(r'^add/$', views.add_profile, name='add'),
    url(r'^edit/$', views.edit_profile, name='edit'),
    url(r'^profile-edit-subjects-hours/$', views.save_new_hoursno_on_profile, name='profile-edit-subjects-hours'),
    url(r'^profile-add-subjects/$', views.add_subject_to_profile, name='profile-add-subjects'),
    url(r'^profile-delete-subject/$', views.delete_subject_from_profile, name='profile-delete-subject')
]

groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'
urlpatterns = [
    url(r'^$', views.group_list, name='group_list'),
    url(r'^delete/$', views.delete_group, name='delete'),
    url(r'^add/$', views.add_group, name='add'),
    url(r'^edit/$', views.edit_group, name='edit'),
]

smok/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from users.views import login
from commons.views import common
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^login', login),
    url(r'^login', auth_views.login, name='login'),
    url(r'^logout', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^subjects/', include('subjects.urls')),
    url(r'^schools/', include('school.urls')),
    url(r'^index', common, name='index'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='root'),
    url(r'^teachers/', include('teachers.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^classrooms/', include('classrooms.urls')),
    url(r'^availability/', include('availability.urls')),
    url(r'^profiles/', include('classProfiles.urls')),
    url(r'^timetables/', include('timetables.urls')),
]

classProfiles/models.py
from django.db import models
from django.utils.timezone import now
from subjects.models import Subject

class Grade(models.Model):
    grade = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.grade)

class Class_profile(models.Model):
    class Meta:
        unique_together = (('name', 'grade'),)

    name = models.CharField(max_length=50)
    grade = models.ForeignKey(Grade)
    description = models.CharField(max_length=200, blank=True, default='')
    last_updated_timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return '%s, %s rok' % (self.name, self.grade)

class HoursAmount(models.Model):
    profile = models.ForeignKey(Class_profile)
    subject = models.ForeignKey(Subject)
    hoursno = models.PositiveIntegerField(default=0)

    def get_subject_name(self):
        return self.subject.name

    def __str__(self):
        return str(self.subject)

groups/models.py
# -*- coding: utf-8 -*-
from django.db import models
from school.models import  School
from classProfiles.models import Class_profile


class Group(models.Model):
    class Meta:
        unique_together = ('name',)

    name = models.CharField(max_length=200, verbose_name="Klasa")
    #group_profile = models.CharField(max_length=200, blank=True, default='')
    group_profile = models.ForeignKey(Class_profile, verbose_name="Profil", on_delete=models.SET_NULL, blank=True, null=True)
    number_of_students = models.PositiveIntegerField(blank=True, null=True, default=0)
    school = models.ForeignKey(School, on_delete=models.CASCADE, verbose_name="Szkoła", blank=True, null=True, default=None)
    
    def __str__(self):
        return self.name

classProfiles/forms.py
from django import forms
from .models import Class_profile, HoursAmount

class ClassProfileForm(forms.ModelForm):
    
    class Meta:
        model = Class_profile
        fields = ('name', 'grade', 'description')

class HoursAmountForm(forms.ModelForm):
    class Meta:
        model = HoursAmount
        exclude = ()
        labels = {
            'profile': 'Profil',
            'subject': 'Przedmiot',
            'hoursno': 'L. godzin',
        }

"""
class HoursAmountForm(forms.ModelForm):

    test = forms.ChoiceField()
    #days = forms.ChoiceField(choices=[(x, x) for x in range(1, 32)])
    def __init__(self, *args, **kwargs):
         super(HoursAmountForm, self).__init__(*args, **kwargs)
         self.fields["test"].choices = \
         [(item.subject.name, item.subject.name) for item in HoursAmount.objects.all()]

    class Meta:
        model = HoursAmount
        fields = ('profile', 'hoursno', 'test')
"""
"""
class Customer(models.Model):
  phone_number = models.ForeignKey(PhoneNumber)

class PhoneNumber(models.Model):
  TYPES = (
      ('Cell', 'Cell'),
      ('Home', 'Home'),
      ('Fax', 'Fax'),
      ('Work', 'Work'),
  )
  primary = models.BooleanField(default=False)
  phone_type = models.CharField(max_length=30, choices=TYPES, default='Cell')
  number = models.CharField(max_length=15)
  
from yourapp.models import PhoneNumber    

class CustomerCreateForm(forms.ModelForm):
    '''
    Base form for creating customers
    '''
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Fieldset(
                'Personal Information',
                'phone_number',
            ),
         FormActions(
             Submit('submit' , 'Submit' , css_class='btn btn-success'), 
             Button('cancel' , 'Cancel' , css_class='btn btn-warning', 
                    onclick='javascript:history.go(-1);'), 
             )
         )
         super(CustomerCreateForm, self).__init__(*args, **kwargs)
         self.fields["phone_number"].choices = \
         [(item.number, item.number) for item in PhoneNumber.objects.all()]

         class Meta:
             model = Customer
             exclude = (
                 'create_user',
                 'modify_user'
             )
"""

classProfiles/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Class_profile, HoursAmount
from .forms import ClassProfileForm, HoursAmountForm
from django.core import serializers
from subjects.models import Subject
import re, json
from django.contrib.auth.decorators import login_required

@login_required
def profiles(request):
    username = request.user.username if request.user.is_authenticated else 'niezalogowano'
    #class_profile = Class_profile.objects.order_by('name')
    all_profiles_list = Class_profile.objects.select_related().order_by('name')
    context = {'models': all_profiles_list, 'username': username}
    return render(request, 'class-profiles.html', context)
"""
def custom_form_field_callback(field, **kwargs):
    #subjects_query = Subject.objects.filter(filter_field=filter_value)
    if field.name == "subject":
        #return Subject(queryset= subjects_query)
        pass
    else:
         return field.formfield(**kwargs)
"""
@login_required
def profile(request, profile_id):
    username = request.user.username if request.user.is_authenticated else 'niezalogowano'
    profile = Class_profile.objects.get(pk=profile_id)
    ha_models_in_profile = HoursAmount.objects.filter(profile=profile).order_by('subject')
    context = {'model': profile, 'username': username, 'ha_models_in_profile': ha_models_in_profile}
    return render(request, 'class-profile.html', context)

def add_subject_to_profile(request):
    if request.method == "GET":
        profile_id = request.GET['profile-id']
        profile = Class_profile.objects.get(pk=profile_id)
        ha_models_in_profile = HoursAmount.objects.filter(profile=profile)

        wanted_items = set()
        for s in Subject.objects.all():
            if s not in (ha.subject for ha in ha_models_in_profile):
                wanted_items.add(s.pk)
        data = serializers.serialize('json', Subject.objects.filter(pk__in=wanted_items))
        return HttpResponse(data)

    if request.method == "POST":
        profile_id = int(dict(request.POST)['profile-id'][0])
        existing_profile = Class_profile.objects.get(pk=profile_id)
        response_data = []

        if 'subject-id' in dict(request.POST):
            subjects = dict(request.POST)['subject-id']
            for s in subjects:
                subject = Subject.objects.get(pk=s)
                new_ha = HoursAmount(profile=existing_profile, subject=subject)
                new_ha.save()
                response_data.append(subject.id)

        data = serializers.serialize('json', Subject.objects.filter(pk__in=response_data))
        data = json.loads(data)
        for s in range(len(data)):
            data[s]['profile'] = profile_id

        return HttpResponse(json.dumps(data))

    return HttpResponse('')

def delete_subject_from_profile(request):
    if request.method == "POST":
        subject_id = int(dict(request.POST)['subjectId'][0])
        profile_id = int(dict(request.POST)['profileId'][0])

        HoursAmount.objects.get(profile=Class_profile.objects.get(pk=profile_id), subject=Subject.objects.get(pk=subject_id)).delete()
        return HttpResponse('')
    return HttpResponse('')

def save_new_hoursno_on_profile(request):
    if request.method == "POST":
        try:
            profile_id = request.POST['profile-id']

            for key in request.POST.keys():
                if 'hoursamount' in key:
                    subject_id = re.search('hoursamount-(.+?)-subject', key).group(1)
                    try:
                        hoursamount_record = HoursAmount.objects.get(subject=subject_id, profile = profile_id)
                        new_number_of_hours = int(request.POST[key])
                        if new_number_of_hours != hoursamount_record.hoursno:
                            hoursamount_record.hoursno = new_number_of_hours
                            hoursamount_record.save()
                    except ObjectDoesNotExist:
                        raise Http404("Brak rekordów z requesta w bazie.")
            return HttpResponse('')
        except ObjectDoesNotExist:
            raise Http404("Brak profilu o id %s w bazie." % profile_id)
    else:
        return reverse_lazy('classProfiles:list')

def add_profile(request):
    if request.method == "POST":
        form = ClassProfileForm(request.POST)
        if form.is_valid():
            new_profile = form.save()
            data = serializers.serialize('json', [new_profile])
            return HttpResponse(data)
        return HttpResponse('FAILED')
    else:
        form = ClassProfileForm()
    return HttpResponse(form)

def edit_profile(request):
    if request.method == "POST":
        try:
            print(request.POST)
            record_id = request.POST['id']
            profile = Class_profile.objects.get(pk=record_id)
            form = ClassProfileForm(request.POST, instance=profile)
            if form.is_valid():
                new_profile = form.save()
                data = serializers.serialize('json', [new_profile])
                return HttpResponse(data)
            else:
                return HttpResponse(json.dumps([{'error': 'UNIQUE_NAME_VIOLATED'}]))
        except ObjectDoesNotExist:
            raise Http404("Brak profilu o id %s w bazie." % record_id)
    elif request.method == "GET":
        try:
            record_id = request.GET['id']
            profile = Class_profile.objects.get(pk=record_id)
            form = ClassProfileForm(instance=profile)
        except ObjectDoesNotExist:
            raise Http404("Brak profilu o id %s w bazie." % record_id)
        return HttpResponse(form)

def delete_profile(request):
    if request.method == "POST":
        record_id = request.POST.get("id")
        try:
            profile = Class_profile.objects.get(pk=record_id)
        except ObjectDoesNotExist:
            raise Http404("Brak przedmiotu o id %s w bazie." % record_id)
        profile.delete()
        return HttpResponse()

classProfiles/templates/class-profile.html
<!DOCTYPE html>
{% extends "base_resource.html" %}
{% load static %}

{% block css %}
{{block.super}}
{% endblock %}

{% block js %}
{{block.super}}
<script>
    var editSubjectsHoursURL = "{% url 'classProfiles:profile-edit-subjects-hours' %}";
    var addSubjectToProfileURL = "{% url 'classProfiles:profile-add-subjects' %}";
    var deleteSubjectFromProfileURL = "{% url 'classProfiles:profile-delete-subject' %}";
</script>
<script src="{% static "/js/classProfiles.js" %}"></script>
{% endblock %}

{% block resource-name-header%}Profil {{ model.name }}, {{ model.grade }} rok{% endblock %}

{% block model-definition %}
    <section title="Siatka godzin" data-role="content">

        <form class="base-form edit_subjects_hours" action="" method="POST" id="profile-form">
            {% csrf_token %}
            <div id="input-values">
            {% for ha in ha_models_in_profile %}
                <div id="subject-form-{{ ha.subject.id }}">
                    <div class="form-disp"> <label>Przedmiot:</label><b>{{ ha.subject }}</b>
                        <span id="subj-form-delete-{{ ha.subject.id }}" class="close-profile-subj" onClick="delete_subj({{ ha.subject.id }}, {{ ha.profile.id }}, '{{ ha.subject }}');">&#x232b;</span>
                    </div>
                    <div class="form-disp"> <label>L. godzin:</label> <input type="number" name="hoursamount-{{ ha.subject.id }}-subject" value="{{ ha.hoursno }}" min="0" id="hoursamount-{{ ha.subject.id }}-subject"></div>
                </div>
            {% empty %}
                <p id="noResources">Brak przedmiotów przypisanych do tego profilu.</p>
            {% endfor %}
            </div>
            <input type="hidden" name="profile-id" value="{{ model.id }}" />
            <input disabled="true" id="submit" class="send button form-button" type="submit" name="Submit" value="Zapisz nową l. godzin">
        </form>
    </section>

{% endblock %}

{% block add-resource %}<span onClick="addSubjectToProfile({{ model.id }})" class="button">&#43; nowy przedmiot</span>{% endblock %}
{% block return-button %}
<a class="no-format" href="{% url 'classProfiles:list' %}"><span class="button button-right">Powrót do profili</span></a>
{% endblock %}

{% block success-modal-header%}Uaktualniono profil {{ model.name }}, {{ model.grade }} rok{% endblock %}
{% block success-modal-body%}
Liczba godzin została zaktualizowana.
{% endblock %}

{% block add-subj-modal-header%}Dodaj nowe przedmioty do profilu{% endblock %}
{% block add-subj-modal-body%}
<form action='' method="POST" class="add_subject_to_profile" autocomplete="off">
    {% csrf_token %}
    <div id="addSubjectForm" class="form"></div>
    <input id="addSubjectFormSubmit" class="send button" type="submit" value="Dodaj" />
</form>
{% endblock %}

{% block delete-subj-modal-header%}Czy na pewno chcesz usunąć przedmiot <span class="subjectName"></span> z tego profilu?{% endblock %}
{% block delete-subj-modal-body%}
<button class="cancel send" onClick="closeDeleteSubjectModal();">Anuluj</button>
{% endblock %}

classProfiles/templates/class-profiles.html
<!DOCTYPE html>
{% extends "base_resources_list.html" %}
{% load static %}

{% block css %}
{{block.super}}
{% endblock %}

{% block js %}
{{block.super}}
<script>
    var addURL = "{% url 'classProfiles:add' %}";
    var editURL = "{% url 'classProfiles:edit' %}";
    var deleteURL = "{% url 'classProfiles:delete' %}";
</script>
<script src="{% static "/js/classProfiles.js" %}"></script>
{% endblock %}

{% block resource-name-header%}Profile klas{% endblock %}

{% block add-resource %}<span id="newItem" class="button">&#43; nowy profil</span>{% endblock %}

{% block list-header-definition %}
<span class="row-content">Profil</span>
<span class="row-content">Klasy</span>
{% endblock %}

{% block model-definition %}
<li id="{{ model.id }}">
    <a class="no-format" href="{% url 'classProfiles:profile' model.id %}">
        <span class="row-content"> <span id="resource-name-{{ model.id }}">{{ model.name }}</span>, <span id="resource-grade-{{ model.id }}">{{ model.grade }}</span> rok</span>
    </a>
    <a class="no-format" href="{% url 'groups:group_list' %}">
        <span class="row-content">{{ model.group_set.all|join:", "|default:"<p>brak</p>" }}</span>
    </a>
    <span class="edit" onClick="edit_item({{ model.id }});">&#x1f589;</span>
    <span id="resource-delete-{{ model.id }}" class="close" onClick="delete_item({{ model.id }}, '{{ model.name }}');">&#x232b;</span>
</li>
{% endblock %}

{% block empty-models-comment %}Brak zapisanych profilów.{% endblock %}

{% block success-modal-header%}Informacja{% endblock %}
{% block success-modal-body%}
Profil o podanej nazwie i roczniku już istnieje.
{% endblock %}

{% block add-modal-header%}Dodaj nowy profil{% endblock %}
{% block add-modal-body%}
<form action='' method="POST" class="add_profile" autocomplete="off">{% csrf_token %}
    <div id="addForm" class="form"></div>
    <input class="send button" type="submit" value="Dodaj" />
</form>
{% endblock %}

{% block edit-modal-header%}Edytuj przedmiot <span class="profileName"></span>{% endblock %}
{% block edit-modal-body%}
<form action='' method="POST" class="edit_profile" autocomplete="off">{% csrf_token %}
    <div id="editForm" class="form"></div>
    <input class="send button" type="submit" value="Zapisz" />
</form>
{% endblock %}

{% block delete-modal-header%}Czy na pewno chcesz usunąć profil <span class="profileName"></span>?{% endblock %}
{% block delete-modal-body%}
<button class="cancel send" onClick="closeDeleteModal();">Anuluj</button>
{% endblock %}