availability/urls.py
from django.conf.urls import include, url

from availability import views

app_name = 'availability'

urlpatterns = [
    #url(r'^$', views.index,name='input'),
	url(r'^(?P<teacher_id>[0-9]+)/$', views.input,name='input'),
	url(r'^save/(?P<teacher_id>[0-9]+)/$', views.save,name='save'),
	#url(r'^add/$', views.TeacherCreate.as_view(),name='add'),
	#url(r'^(?P<pk>[0-9]+)/rm/$', views.TeacherDelete.as_view(),name='delete'),
]

classProfiles/urls.py
from django.conf.urls import url

from . import views

app_name = 'classProfiles'
urlpatterns = [
    url(r'^$', views.profiles, name='list'),
    url(r'^(?P<profile_id>[0-9]+)/$', views.profile, name='profile'),
    url(r'^delete/$', views.delete_profile, name='delete'),
    url(r'^add/$', views.add_profile, name='add'),
    url(r'^edit/$', views.edit_profile, name='edit'),
    url(r'^profile-edit-subjects-hours/$', views.save_new_hoursno_on_profile, name='profile-edit-subjects-hours'),
    url(r'^profile-add-subjects/$', views.add_subject_to_profile, name='profile-add-subjects'),
    url(r'^profile-delete-subject/$', views.delete_subject_from_profile, name='profile-delete-subject')
]

groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'
urlpatterns = [
    url(r'^$', views.group_list, name='group_list'),
    url(r'^delete/$', views.delete_group, name='delete'),
    url(r'^add/$', views.add_group, name='add'),
    url(r'^edit/$', views.edit_group, name='edit'),
]

smok/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from users.views import login
from commons.views import common
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    # url(r'^login', login),
    url(r'^login', auth_views.login, name='login'),
    url(r'^logout', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^subjects/', include('subjects.urls')),
    url(r'^schools/', include('school.urls')),
    url(r'^index', common, name='index'),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='root'),
    url(r'^teachers/', include('teachers.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^classrooms/', include('classrooms.urls')),
    url(r'^availability/', include('availability.urls')),
    url(r'^profiles/', include('classProfiles.urls')),
    url(r'^timetables/', include('timetables.urls')),
]

subjects/urls.py
from django.conf.urls import url

from . import views

app_name = 'subjects'
urlpatterns = [
    url(r'^$', views.subjects, name='list'),
    url(r'^delete/$', views.delete_subject, name='delete'),
    url(r'^add/$', views.add_subject, name='add'),
    url(r'^edit/$', views.edit_subject, name='edit'),
]

teachers/urls.py
from django.conf.urls import include, url
from teachers import views

app_name = 'teachers'

urlpatterns = [
    url(r'^$', views.teachers, name='list'),
    url(r'^delete/$', views.delete_teacher, name='delete'),
    url(r'^add/$', views.add_teacher, name='add'),
    url(r'^edit/$', views.edit_teacher, name='edit'),
    url(r'^add-teacher-assignment/$', views.add_teacher_assignment, name='add-teacher-assignment'),
    url(r'^delete-teacher-assignment/$', views.delete_teacher_assignment, name='delete-teacher-assignment')
]

teachers/models.py
from django.db import models
from groups.models import Group
from subjects.models import Subject


class Teacher(models.Model):
    class Meta:
        unique_together = ('first_name', 'last_name',)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    def __str__(self):
        return self.last_name + ' ' + self.first_name


class TeacherClassSubject(models.Model):
    class Meta:
        unique_together = ('teacher', 'subject', 'group',)
        ordering = ['group']
    teacher = models.ForeignKey(Teacher)
    subject = models.ForeignKey(Subject)
    group = models.ForeignKey(Group)

teachers/forms.py
from django import forms
from .models import Teacher, TeacherClassSubject


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ('first_name', 'last_name')


class TeacherClassSubjectForm(forms.ModelForm):
    class Meta:
        model = TeacherClassSubject
        fields = ('subject', 'group')

teachers/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from .models import Teacher, TeacherClassSubject
from .forms import TeacherForm, TeacherClassSubjectForm
from django.core import serializers
from subjects.models import Subject
import re, json
from django.contrib.auth.decorators import login_required
from classProfiles.models import Class_profile, HoursAmount
from groups.models import Group
from itertools import chain
from datetime import date, datetime
from django.db import IntegrityError


@login_required
def teachers(request):
    all_teachers_list = Teacher.objects.select_related().order_by('last_name')
    teachers_list_custom = [[teacher] for teacher in all_teachers_list]

    for t in teachers_list_custom:
        hours_total = 0
        t.append(hours_total)
        t.append([])
        tcs_queryset = TeacherClassSubject.objects.filter(teacher=t[0])
        for i, tcs in enumerate(tcs_queryset):
            group = tcs.group
            profile = group.group_profile
            subject = tcs.subject
            t[2].append([])
            t[2][i].append(tcs)
            t[2][i].append('MISSING')
            for ha in HoursAmount.objects.filter(profile=profile, subject=subject):
                t[2][i][1] = str(ha.hoursno)
                hours_total += ha.hoursno
                #hours_assignment['teacher'+str(t[0].id)+'-subject'+str(subject.id)+'-group'+str(group.id)] = ha.hoursno
            t[1] = hours_total
            """
            [[<Teacher: Alala Pawel>, 0, []], 
                [<Teacher: Nowy Adam>, 10, [[<TeacherClassSubject: TeacherClassSubject object>, '2'], [<TeacherClassSubject: TeacherClassSubject object>, 'MISSING'], [<TeacherClassSubject: TeacherClassSubject object>, '8'], [<TeacherClassSubject: TeacherClassSubject object>, 'MISSING'], [<TeacherClassSubject: TeacherClassSubject object>, 'MISSING']]]]
            """

    context = {'models': all_teachers_list, 'teachers_list_custom': teachers_list_custom}
    return render(request, 'teachers.html', context)


def json_serial(obj):
    """JSON serializer for objects not serializable by default json code"""

    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError ("Type %s not serializable" % type(obj))

def add_teacher_assignment(request):

    if request.method == "GET":
        teacher = Teacher.objects.get(pk=int(dict(request.GET)['teacher-id'][0]))
        teacher_name = teacher.last_name + ' ' + teacher.first_name
        subjects_list = list(Subject.objects.order_by('name').values())
        groups_list = list(Group.objects.order_by('name').values())
        combined_subj_group = json.dumps({'subjects': subjects_list, 'groups': groups_list, 'teacher': teacher_name}, default=json_serial, ensure_ascii=False)

        return HttpResponse(combined_subj_group)

    if request.method == "POST":

        teacher_id = int(dict(request.POST)['teacher-id'][0])
        subject_id = int(dict(request.POST)['subject'][0])
        group_id = int(dict(request.POST)['group'][0])

        teacher = Teacher.objects.get(pk=teacher_id)
        subject = Subject.objects.get(pk=subject_id)
        subject_name = subject.name + ' (' + subject.code + ')'
        group = Group.objects.get(pk=group_id)

        try:
            new_tcs = TeacherClassSubject(teacher=teacher, subject=subject, group=group)
            new_tcs.save()
        except IntegrityError:
            print('su ORA: integrity constraint')
            return HttpResponse(json.dumps({'error': 'UNIQUE_CONSTRAINT_VIOLATED'}))

        tcs_queryset = TeacherClassSubject.objects.filter(teacher=teacher)
        hours_total = 0
        for i, tcs in enumerate(tcs_queryset):
            for ha in HoursAmount.objects.filter(profile=tcs.group.group_profile, subject=tcs.subject):
                hours_total += ha.hoursno

        try:
            assignment_hours = HoursAmount.objects.get(profile=group.group_profile, subject=subject).hoursno
        except HoursAmount.DoesNotExist:
            assignment_hours = 'MISSING'

        response_json = json.dumps({'subject': subject_name, 'teacher_id': teacher_id, 'group': group.name, 'new_tcs': new_tcs.pk, 'total_hours': hours_total, 'assignment_hours': assignment_hours, 'group_profile_id': group.group_profile.pk},
                                         default=json_serial, ensure_ascii=False)

        return HttpResponse(response_json)

    return HttpResponse('')

def delete_teacher_assignment(request):
    if request.method == "POST":
        assignment_id = int(dict(request.POST)['assignmentId'][0])

        tcs = TeacherClassSubject.objects.get(pk=assignment_id)
        tcs.delete()

        tcs_queryset = TeacherClassSubject.objects.filter(teacher=tcs.teacher)
        hours_total = 0
        for i, tcs in enumerate(tcs_queryset):
            for ha in HoursAmount.objects.filter(profile=tcs.group.group_profile, subject=tcs.subject):
                hours_total += ha.hoursno

        return HttpResponse(json.dumps({'hours_total': hours_total}))
    return HttpResponse('')

def add_teacher(request):
    if request.method == "POST":
        form = TeacherForm(request.POST)
        if form.is_valid():
            new_teacher = form.save()
            data = serializers.serialize('json', [new_teacher])
            return HttpResponse(data)
        return HttpResponse('FAILED')
    else:
        form = TeacherForm()
    return HttpResponse(form)

def edit_teacher(request):
    if request.method == "POST":
        try:
            record_id = request.POST['id']
            teacher = Teacher.objects.get(pk=record_id)
            form = TeacherForm(request.POST, instance=teacher)
            if form.is_valid():
                new_teacher = form.save()
                data = serializers.serialize('json', [new_teacher])
                return HttpResponse(data)
            else:
                return HttpResponse(json.dumps([{'error': 'UNIQUE_NAME_VIOLATED'}]))
        except ObjectDoesNotExist:
            raise Http404("Brak nauczyciela o id %s w bazie." % record_id)
    elif request.method == "GET":
        try:
            record_id = request.GET['id']
            teacher = Teacher.objects.get(pk=record_id)
            form = TeacherForm(instance=teacher)
        except ObjectDoesNotExist:
            raise Http404("Brak profilu o id %s w bazie." % record_id)
        return HttpResponse(form)

def delete_teacher(request):
    if request.method == "POST":
        record_id = request.POST.get("id")
        try:
            teacher = Teacher.objects.get(pk=record_id)
        except ObjectDoesNotExist:
            raise Http404("Brak nauczyciela o id %s w bazie." % record_id)
        teacher.delete()
        return HttpResponse()

teachers/templates/teachers.html
<!DOCTYPE html>
{% extends "base_custom_structure_resources_list.html" %}
{% load static %}

{% block css %}
{{block.super}}
{% endblock %}

{% block js %}
{{block.super}}
<script>
    var addURL = "{% url 'teachers:add' %}";
    var editURL = "{% url 'teachers:edit' %}";
    var deleteURL = "{% url 'teachers:delete' %}";
    var addAssignmentURL = "{% url 'teachers:add-teacher-assignment' %}";
    var deleteAssignmentURL = "{% url 'teachers:delete-teacher-assignment' %}";
</script>
<script src="{% static "/js/teachers.js" %}"></script>
{% endblock %}

{% block resource-name-header%}Nauczyciele{% endblock %}

{% block add-resource %}<span id="newItem" class="button">&#43; nowy nauczyciel</span>{% endblock %}

{% block custom-datastructure %}
<li id="list-header">
    <span class="row-content" style="width:200px;">Nazwisko</span>
    <span class="row-content" style="width:200px;">Imię</span>
    <span class="row-content" style="width:200px;">Godzin łącznie</span>
    <span class="row-content-longer">Przydział przedmiotu i grupy</span>
</li>

{% for teacher, total_hours, assignments in teachers_list_custom %}
    <li id="{{ teacher.id }}">
        <span class="row-content" style="width:200px;"><span id="resource-lastName-{{ teacher.id }}" class="list-element">{{ teacher.last_name }}</span></span>
        <span class="row-content" style="width:200px;"><span id="resource-firstName-{{ teacher.id }}" class="list-element">{{ teacher.first_name }}</span></span>
        <span class="row-content" style="width:200px;"><span id="resource-hours-{{ teacher.id }}" class="list-element">{{ total_hours }}</span></span>
        <span class="row-content-longer"><span class="list-element">
            <div id="assignments-container-teacher-{{ teacher.id }}">
               {% for assignment in assignments %}
                   <span id="teacher-{{ teacher.id }}-assignment-{{ assignment.0.id }}" class="list-element">
                   &#9679; <a class="no-format" href="{% url 'subjects:list' %}">{{ assignment.0.subject }}</a> w grupie <a class="no-format" href="{% url 'groups:group_list' %}">{{ assignment.0.group }}</a> (<a class="no-format" href="{% url 'classProfiles:profile' assignment.0.group.group_profile.id %}">{% if assignment.1 == "MISSING" %}<span class="discraparency-warning">brak przedmiotu w profilu grupy</span>{% else %}{{ assignment.1 }} godz. w tyg.{% endif %}</a>) <span id="resource-delete-assignment-{{ assignment.0.id }}" class="close-secondary" onClick="delete_assignment({{ assignment.0.id }}, {{ teacher.id }}, '{{ assignment.0.subject }} - {{ assignment.0.group }}');">&#x2717;</span>
                   </span>
               {% endfor %}
            </div>
            </br>
            <span onClick="addAssignmentToTeacher({{ teacher.id }})" class="button-secondary">&#43; nowy przydział</span>
        </span></span>
        <span><a href="{% url 'availability:input' teacher.id%}" class="calendar">&#128197;</a></span>
        <span class="edit" onClick="edit_item({{ teacher.id }});">&#x1f589;</span>
        <span id="resource-delete-{{ teacher.id }}" class="close" onClick="delete_item({{ teacher.id }}, '{{ teacher }}');">&#x232b;</span>
    </li>
{% empty %}
    <p id="noResources">Brak zapisanych nauczycieli.</p>
{% endfor %}

{% endblock %}



{% block success-modal-header%}Informacja{% endblock %}
{% block success-modal-body%}
Nauczyciel o podanym imieniu i nazwisku już istnieje.
{% endblock %}

{% block add-modal-header%}Dodaj nowego nauczyciela{% endblock %}
{% block add-modal-body%}
<form action='' method="POST" class="add_teacher" autocomplete="off">{% csrf_token %}
    <div id="addForm" class="form"></div>
    <input class="send button" type="submit" value="Dodaj" />
</form>
{% endblock %}

{% block edit-modal-header%}Edytuj nauczyciela{% endblock %}
{% block edit-modal-body%}
<form action='' method="POST" class="edit_teacher" autocomplete="off">{% csrf_token %}
    <div id="editForm" class="form"></div>
    <input class="send button" type="submit" value="Zapisz" />
</form>
{% endblock %}

{% block delete-modal-header%}Czy na pewno chcesz usunąć nauczyciela <span class="teacherName"></span>?{% endblock %}
{% block delete-modal-body%}
<button class="cancel send" onClick="closeDeleteModal();">Anuluj</button>
{% endblock %}

{% block info-ora-modal-header%}Informacja{% endblock %}
{% block info-ora-modal-body%}
Nauczyciel ma już przydzielony ten przedmiot do tej grupy.
{% endblock %}

{% block add-assignment-modal-header%}Dodaj nowy przydział dla <span class="teacherName"></span>{% endblock %}
{% block add-assignment-modal-body%}
<form action='' method="POST" class="add_assignment" autocomplete="off">{% csrf_token %}
    <div id="addAssignmentForm" class="form"></div>
    <input class="send button" type="submit" value="Dodaj" />
</form>
{% endblock %}

{% block delete-assignment-modal-header%}Czy na pewno chcesz usunąć przydział <span class="assignmentName"></span> u nauczyciela <span class="teacherName"></span>?{% endblock %}
{% block delete-assignment-modal-body%}
<button class="cancel send" onClick="closeDeleteAssignmentModal();">Anuluj</button>
{% endblock %}